
buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'

group = 'com.yourname.stationsticker'
version = '1.1.0+1.20.1'
archivesBaseName = 'StationStickerMTR'
java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                stationsticker {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net' }

    flatDir {
        dirs 'libs'
    }

    mavenCentral()
}

dependencies {
    // Forge
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'

    implementation fg.deobf(files('libs/MTR-forge-4.0.3+1.20.1.jar'))
}

jar {
    manifest {
        attributes([
                "Specification-Title": "stationsticker",
                "Specification-Vendor": "stationstickerauthors",
                "Specification-Version": "1",
                "Implementation-Title": project.name,
                "Implementation-Version": project.version,
                "Implementation-Vendor" :"stationstickerauthors",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
task copyToMods(type: Copy) {
    from 'build/libs'
    into 'C:/Users/aleks/AppData/Roaming/.minecraft/versions/проверка мода 1.20.1/mods'
    include '*.jar'
}

build.finalizedBy copyToMods