modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="stationsticker"
version="1.0.0"
displayName="Station Sticker"
description='''
Adds customizable station name stickers that automatically display the station name and line color.
    Place them along platforms for better navigation, just like in real metro systems!
'''
authors="Tr1nity"
logoFile="logo.png"
credits="Thanks to the MTR team and kykko"
license="MIT"

[[dependencies.stationsticker]]
modId="forge"
mandatory=true
versionRange="[43.4.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.stationsticker]]
modId="mtr"
mandatory=false  # ИЗМЕНЕНО С true НА false!
versionRange="[4.0.2,)"
ordering="AFTER"
side="BOTH"